name: kaggle-gcloud-genai
channels:
  - conda-forge
  - h20ai
  - defaults
dependencies:
  - python=3.10.14
  - jupyter
  - jupyterlab
  - ipywidgets
  - notebook
  - tensorflow
  - pytorch
  - torchvision
  - pytorch-lightning
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - h2o
  - optuna
  - shap
  - pandas
  - numpy
  - scipy
  - statsmodels
  - plotly
  - seaborn
  - spacy
  - gensim
  - nltk
  - pillow
  - scikit-image
  - fastapi
  - uvicorn
  - flask
  - apache-beam
  - python-dotenv
  - pip
  - pip:
    - eli5
    - featuretools
    - ydata-profiling
    - prophet
    - transformers
    - accelerate
    - datasets
    - albumentations
    - fastai
    - opencv-python
    - bigframes
    - aiobotocore
    - google-cloud-bigquery
    - google-cloud-storage
    - google-cloud-aiplatform
    - google-cloud-translate
    - google-cloud-vision
    - google-cloud-language
    - google-cloud-pubsub
    - google-cloud-monitoring
    - google-cloud-artifact-registry
    - google-cloud-iam
    - google-auth
    - google-api-python-client
    - google-auth-oauthlib
    - google-auth-httplib2
    - google-generativeai
    - cloudpathlib